FROM ubuntu:bionic
LABEL maintainer="Lks Developers <dev@lksfoundation.org>"
LABEL description="Dockerised LksCore"

ARG USER_ID
ARG GROUP_ID
ARG TAG

ENV HOME /home/lks

# add user with specified (or default) user/group ids
ENV USER_ID ${USER_ID:-1000}
ENV GROUP_ID ${GROUP_ID:-1000}
RUN groupadd -g ${GROUP_ID} lks && \
    useradd -u ${USER_ID} -g lks -s /bin/bash -m -d /home/lks lks  && \
    mkdir /home/lks/.lkscore && \
    chown ${USER_ID}:${GROUP_ID} -R /home/lks

RUN apt-get update && \
    apt-get -y install --no-install-recommends \
    wget \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN mach=$(uname -m) \
      && case $mach in aarch64) arch="aarch64-linux-gnu"; ;; x86_64) arch="x86_64-linux-gnu"; ;;  *) echo "ERROR: Machine type $mach not supported."; ;; esac \
      && wget https://github.com/LKSCOIN/lkscoin-core/releases/download/v${TAG}/lkscore-${TAG}-$arch.tar.gz -P /tmp \
      && tar -xvf /tmp/lkscore-*.tar.gz -C /tmp/ \
      && cp /tmp/lkscore*/bin/*  /usr/local/bin \
      && rm -rf /tmp/lkscore* \
      && chmod a+x /usr/local/bin/*

USER lks

VOLUME ["/home/lks"]

COPY docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 9998 9999 19998 19999

WORKDIR /home/lks
